filter:
    paths: [ 'src/*' ]

build_failure_conditions:
    - 'elements.rating(<= D).exists'
    - 'elements.rating(<= B).new.exists'
    - 'issues.label("coding-style").new.exists'
    - 'issues.severity(>= MAJOR).new.exists'

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
        braces:
            classes_functions:
                class: new-line
                function: new-line
                closure: end-of-line
            if:
                opening: end-of-line
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

checks:
    php:
        code_rating: true
        duplication: true
        verify_property_names: true
        uppercase_constants: true
        remove_extra_empty_lines: true
        properties_in_camelcaps: true
        parameters_in_camelcaps: true
        overriding_parameter: true
        optional_parameters_at_the_end: true
        function_in_camel_caps: true
        encourage_single_quotes: true
        classes_in_camel_caps: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        avoid_perl_style_comments: true
        avoid_usage_of_logical_operators: true
        no_exit: false
        no_unnecessary_final_modifier: false
        overriding_private_members: false

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
