<?php

namespace Behat\Behat\Definition\Pattern;

class SimpleStepMethodNameGenerator implements StepMethodNameGenerator
{
    /**
     * @internal
     *
     * @deprecated provided only for BC, to allow the ContextSnippetGenerator to continue doing this cleanup for any
     *             steps that were generated by a third-party PatternPolicy that does not use our StepMethodNameGenerator
     */
    public static function cleanupMethodName(string $name): string
    {
        if (0 !== strlen($name)) {
            $name[0] = strtolower($name[0]);

            return $name;
        }

        return 'stepDefinition1';
    }

    public function generate(string $stepTextWithoutPlaceholders): string
    {
        $name = preg_replace('/[^a-zA-Z\_\ ]/', '', $stepTextWithoutPlaceholders);

        $name = str_replace(' ', '', ucwords($name));

        return self::cleanupMethodName($name);
    }
}
